name: Build OpenCV for Windows and macOS

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-opencv.yml'
      - 'opencv-options.txt'
      - 'mingw-gcc.txt'
      - 'cl_version'

env:
  OPENCV_VERSION: "4.14.0"

jobs:
  build_macos_intel:
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v7
    - name: Install or Download Dependencies
      run: |
        brew install curl unzip 7zip
        curl -L https://github.com/opencv/opencv/archive/${{ env.OPENCV_VERSION }}.tar.gz -o opencv-${{ env.OPENCV_VERSION }}.tar.gz
        cmake --version
        ls -la

    - name: Build OpenCV-${{ env.OPENCV_VERSION }}-x86_64
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        tar -xf opencv-${{ env.OPENCV_VERSION }}.tar.gz
        rm -f opencv-${{ env.OPENCV_VERSION }}.tar.gz
        echo ~~~~~~~~~~~~ x86_64 build begin ~~~~~~~~~~~~
        cflags="-arch x86_64 -isysroot macosx -Wno-unused-local-typedef -Wno-unused-function -DNDEBUG -g -O3 -pipe -fPIC -fcxx-exceptions"
        export LDFLAGS="-arch x86_64 -stdlib=libc++"
        export CFLAGS="$cflags"
        export CXXFLAGS="$cflags"
        which ar ranlib clang clang++
        mkdir build-x86_64
        cd build-x86_64
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "Unix Makefiles" -DBUILD_LIST=core,imgcodecs -DBUILD_opencv_gapi=OFF -DWITH_AVIF=OFF \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-macosx-x86_64 \
            -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_SYSROOT=macosx \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 \
           `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            make -j4 && make install
        rm -rf ./*
        cd ..
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-macosx-x86_64 && ls -la && cd lib && ls -la && cd ..
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-x86_64.7z *
        cd ..
        echo ~~~~~~~~~~~~ x86_64 build end ~~~~~~~~~~~~

    - name: Upload opencv-${{ env.OPENCV_VERSION }}-x86_64
      uses: softprops/action-gh-release@v3
      with:
        tag_name: opencv-${{ env.OPENCV_VERSION }}
        name: Latest build of opencv-${{ env.OPENCV_VERSION }} for macOS
        draft: false
        prerelease: true
        make_latest: false
        files: |
          ./opencv-${{ env.OPENCV_VERSION }}-*.7z

  build_macos_arm64:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7

    - name: Install or Download Dependencies
      run: |
        brew install curl unzip 7zip
        curl -L https://github.com/opencv/opencv/archive/${{ env.OPENCV_VERSION }}.tar.gz -o opencv-${{ env.OPENCV_VERSION }}.tar.gz
        brew install cmake
        cmake --version
        ls -la

    - name: Build OpenCV-${{ env.OPENCV_VERSION }}-arm64
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        tar -xf opencv-${{ env.OPENCV_VERSION }}.tar.gz
        rm -f opencv-${{ env.OPENCV_VERSION }}.tar.gz
        echo ~~~~~~~~~~~~ arm64 build begin ~~~~~~~~~~~~
        cflags="-arch arm64 -isysroot macosx -Wno-unused-local-typedef -Wno-unused-function -DNDEBUG -g -O3 -pipe -fPIC -fcxx-exceptions"
        export LDFLAGS="-arch arm64 -stdlib=libc++"
        export CFLAGS="$cflags"
        export CXXFLAGS="$cflags"
        which ar ranlib clang clang++
        mkdir build-arm64
        cd build-arm64
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "Unix Makefiles" -DBUILD_LIST=core,imgcodecs -DBUILD_opencv_gapi=OFF -DWITH_AVIF=OFF \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-macosx-arm64 \
            -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_OSX_SYSROOT=macosx \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 \
           `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            make -j4 && make install
        rm -rf ./*
        cd ..
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-macosx-arm64 && ls -la && cd lib && ls -la && cd ..
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-arm64.7z *
        cd ..
        echo ~~~~~~~~~~~~ arm64 build end ~~~~~~~~~~~~

    - name: Upload opencv-${{ env.OPENCV_VERSION }}
      uses: softprops/action-gh-release@v3
      with:
        tag_name: opencv-${{ env.OPENCV_VERSION }}
        name: Latest build of opencv-${{ env.OPENCV_VERSION }} for macOS
        draft: false
        prerelease: false
        make_latest: true
        files: |
          ./opencv-${{ env.OPENCV_VERSION }}-*.7z

  make_macos_universal:
    needs: [build_macos_intel, build_macos_arm64]
    runs-on: macos-15-intel
    steps:
    - uses: actions/checkout@v7
    - name: Install or Download Dependencies
      run: |
        brew install curl 7zip
        curl -L https://github.com/nonwill/nw3rdBuild/releases/download/opencv-${{ env.OPENCV_VERSION }}/opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-x86_64.7z -o opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-x86_64.7z
        curl -L https://github.com/nonwill/nw3rdBuild/releases/download/opencv-${{ env.OPENCV_VERSION }}/opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-arm64.7z -o opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-arm64.7z
        export WSP_ROOT=$PWD
        7z x opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-x86_64.7z -r -o$WSP_ROOT/x86_64
        7z x opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-arm64.7z -r -o$WSP_ROOT/arm64
        ls -la

    - name: Make OpenCV-${{ env.OPENCV_VERSION }}-Universal
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        ocv_ver=${{ env.OPENCV_VERSION }}
        mkdir -p $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-macosx-universal/lib
        cp -R $WSP_ROOT/x86_64/include $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-macosx-universal
        lipo \
                $WSP_ROOT/x86_64/lib/libopencv_world.${{ env.OPENCV_VERSION }}.dylib \
                $WSP_ROOT/arm64/lib/libopencv_world.${{ env.OPENCV_VERSION }}.dylib \
                -create -output $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-macosx-universal/lib/libopencv_world${ocv_ver//\.}.dylib
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-macosx-universal && ls -la && cd lib && ls -la && cd ..
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-macOS-10.10-universal.7z *
        cd ..

    - name: Get date and Cl version
      id: vars
      shell: bash
      run: |
        echo "update_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - uses: andreaswilli/delete-release-assets-action@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: opencv-${{ env.OPENCV_VERSION }}
        deleteOnlyFromDrafts: false

    - name: Upload opencv-${{ env.OPENCV_VERSION }}
      uses: softprops/action-gh-release@v3
      with:
        tag_name: opencv-${{ env.OPENCV_VERSION }}
        name: Latest build of opencv-${{ env.OPENCV_VERSION }} for macOS
        body: |
          date: ${{ steps.vars.outputs.update_date }}
        draft: false
        prerelease: false
        make_latest: true
        files: |
          ./opencv-${{ env.OPENCV_VERSION }}-*.7z

  build_with_windows-2019:
    needs: make_macos_universal
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v7

    - name: Install or Download Dependencies
      run: |
        choco install curl unzip 7zip -y
        choco install cmake -y
        cmake --version
        mkdir deps
        cd deps && mkdir mingw64 && cd ..
        curl -L https://download.qt.io/official_releases/jom/jom.zip -o jom.zip
        unzip jom.zip -d ${{ github.workspace }}/deps/jom
        curl -L https://github.com/opencv/opencv/archive/${{ env.OPENCV_VERSION }}.tar.gz -o opencv-${{ env.OPENCV_VERSION }}.tar.gz
        curl -L https://github.com/nonwill/mingw-distro/releases/download/mingw64-gcc15-crt_latest/mingw-w64+gcc-i686-all.7z -o mingw-w64_gcc-i686-all.7z
        curl -L https://github.com/nonwill/mingw-distro/releases/download/mingw64-gcc15-crt_latest/mingw-w64+gcc-x86_64-all.7z -o mingw-w64_gcc-x86_64-all.7z
        dir
        ${{ github.workspace }}/deps/jom/jom.exe /VERSION

    - name: MinGW Build OpenCV-${{ env.OPENCV_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export USER_MINGW_DIR=$WSP_ROOT/deps/mingw64
        tar -xf opencv-${{ env.OPENCV_VERSION }}.tar.gz
        rm -f opencv-${{ env.OPENCV_VERSION }}.tar.gz
        mkdir build
        echo ~~~~~~~~~~~~ mingw32 build prepare ~~~~~~~~~~~~
        7z x mingw-w64_gcc-i686-all.7z -r -o$USER_MINGW_DIR
        rm -f mingw-w64_gcc-i686-all.7z
        export PATH=$USER_MINGW_DIR/bin:$PATH
        gcc -v
        echo ~~~~~~~~~~~~ mingw32 build begin ~~~~~~~~~~~~
        cd build
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "MinGW Makefiles" -DBUILD_LIST=core,imgcodecs -DBUILD_opencv_gapi=OFF -DWITH_AVIF=OFF \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64 \
            `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            mingw32-make -j4 && mingw32-make install
        rm -rf ./*
        cd ..
        strip $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64/x64/mingw/bin/*.dll
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-mingw64-i686.7z *
        cd ..
        echo ~~~~~~~~~~~~ mingw32 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64
        rm -rf $USER_MINGW_DIR/*
        echo ~~~~~~~~~~~~ mingw64 build prepare ~~~~~~~~~~~~
        7z x mingw-w64_gcc-x86_64-all.7z -r -o$USER_MINGW_DIR
        rm -f mingw-w64_gcc-x86_64-all.7z
        gcc -v
        echo ~~~~~~~~~~~~ mingw64 build begin ~~~~~~~~~~~~
        cd build
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "MinGW Makefiles" -DBUILD_LIST=core,imgcodecs -DBUILD_opencv_gapi=OFF -DWITH_AVIF=OFF \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64 \
            `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            mingw32-make -j4 && mingw32-make install
        rm -rf ./*
        cd ..
        strip $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64/x64/mingw/bin/*.dll
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-mingw64-x86_64.7z *
        cd ..
        echo ~~~~~~~~~~~~ mingw64 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64

    - name: Setup msvc2019 x64 Environment
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
        toolset: 14.29

    - name: Get date and Cl version
      id: vars
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export USER_MINGW_DIR=$WSP_ROOT/deps/mingw64
        export PATH=$USER_MINGW_DIR/bin:$PATH
        echo "update_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "vc_install_dir=$VCToolsInstallDir" >> $GITHUB_OUTPUT
        echo "cl_exe_info=$(cl > cl_version 2>&1 && head -n 1 cl_version)" >> $GITHUB_OUTPUT
        echo "gcc_exe_info=$(gcc --version > gcc_version 2>&1 && head -n 1 gcc_version)" >> $GITHUB_OUTPUT
        rm -rf $USER_MINGW_DIR

    - name: msvc2019 x64 Build OpenCV-${{ env.OPENCV_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export PATH=$WSP_ROOT/deps/jom:$PATH
        echo ~~~~~~~~~~~~ msvc2019 build begin ~~~~~~~~~~~~
        cl
        cd build
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "NMake Makefiles" -DBUILD_LIST=core,imgcodecs -DBUILD_opencv_gapi=OFF -DWITH_AVIF=OFF \
            -DCMAKE_MAKE_PROGRAM=$WSP_ROOT/deps/jom/jom.exe \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x64 \
            `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            jom -j4 && jom install
        rm -rf ./*
        cd ..
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x64
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-msvc2019-x64.7z *
        cd ..
        echo ~~~~~~~~~~~~ msvc2019 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x64

    - name: Setup msvc2019 x86 Environment
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: amd64_x86
        toolset: 14.29

    - name: msvc2019 x86 Build OpenCV-${{ env.OPENCV_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export PATH=$WSP_ROOT/deps/jom:$PATH
        echo ~~~~~~~~~~~~ msvc2019 build begin ~~~~~~~~~~~~
        cl
        cd build
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "NMake Makefiles" -DBUILD_LIST=core,imgcodecs -DBUILD_opencv_gapi=OFF -DWITH_AVIF=OFF \
            -DCMAKE_MAKE_PROGRAM=$WSP_ROOT/deps/jom/jom.exe \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x86 \
            `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            jom -j4 && jom install
        rm -rf ./*
        cd ..
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x86
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-msvc2019-x86.7z *
        cd ..
        echo ~~~~~~~~~~~~ msvc2019 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x86

    - name: Upload opencv-${{ env.OPENCV_VERSION }}
      uses: softprops/action-gh-release@v3
      with:
        tag_name: opencv-${{ env.OPENCV_VERSION }}
        name: Latest build of opencv-${{ env.OPENCV_VERSION }} for macOS and Windows
        body: |
          date: ${{ steps.vars.outputs.update_date }}
          cl: ${{ steps.vars.outputs.cl_exe_info }}
          gcc: ${{ steps.vars.outputs.gcc_exe_info }}
          source: https://github.com/opencv/opencv/archive/${{ env.OPENCV_VERSION }}.tar.gz
        draft: false
        prerelease: false
        make_latest: true
        files: |
          ./opencv-${{ env.OPENCV_VERSION }}-*.7z
