name: Build protobuf cpp with mingw64 and msvc2019

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-protobuf-v2112.yml'
      - 'protobuf-options.txt'
      - 'mingw-gcc.txt'
      - 'cl_version'

env:
  PROTOBUF_VERSION: "21.12"

jobs:
  macos-shared:
    if: true
    name: ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            arch: arm64
          - os: macos-15-intel
            arch: universal

    steps:
    - name: Cache build result for ${{ env.PROTOBUF_VERSION }}
      id: cache-build-result
      uses: actions/cache@v4
      with:
          path: protobuf-osx-${{ matrix.arch }}-${{ env.PROTOBUF_VERSION }}
          key: protobuf-osx-${{ matrix.arch }}-${{ env.PROTOBUF_VERSION }}-cache-v2

    - name: Action Checkout
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      uses: actions/checkout@v7

    - name: Install or Download Dependencies
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      run: |
          brew install curl 7zip tree
          arch=${{ matrix.arch }}
          if [[ $arch == arm64 ]]; then
            brew install cmake
          fi
          cmake --version

          curl -L https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOBUF_VERSION }}/protobuf-cpp-3.${{ env.PROTOBUF_VERSION }}.tar.gz -o protobuf-cpp-3.${{ env.PROTOBUF_VERSION }}.tar.gz
          ls -la

          tar -xf protobuf-cpp-3.${{ env.PROTOBUF_VERSION }}.tar.gz
          mv protobuf-3.${{ env.PROTOBUF_VERSION }} protobuf-${{ env.PROTOBUF_VERSION }}
          rm -f protobuf-cpp-3.${{ env.PROTOBUF_VERSION }}.tar.gz

          cd protobuf-${{ env.PROTOBUF_VERSION }}
          cat ../protobuf-v3.21.12.patch | patch -p1 --verbose || exit 1
          cat ../protobuf-v3.21.12-a2859cc.patch | patch -p1 --verbose || exit 1
          cd ..

    - name: Build Protocol Buffers-${{ env.PROTOBUF_VERSION }}-${{ matrix.arch }}
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      id: vars
      shell: bash
      run: |
          which ar ranlib clang clang++

          echo ~~~~~~~~~~~~ arm64 build begin ~~~~~~~~~~~~
          arch="arm64"
          artifact1=protobuf-osx-$arch-${{ env.PROTOBUF_VERSION }}
          dst_dir=$PWD/$artifact1

          cflags="-arch $arch -isysroot macosx -Wno-unused-local-typedef -Wno-unused-function -DNDEBUG -g -O3 -pipe -fPIC -fcxx-exceptions"
          export LDFLAGS="-arch $arch -stdlib=libc++"
          export CFLAGS="$cflags"
          export CXXFLAGS="$cflags"

          mkdir build-$arch
          cd build-$arch

          cmake ../protobuf-${{ env.PROTOBUF_VERSION }} \
            -G "Unix Makefiles" \
            -DCMAKE_INSTALL_PREFIX=$dst_dir \
            -DCMAKE_OSX_ARCHITECTURES="$arch" -DCMAKE_OSX_SYSROOT=macosx \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 \
            `cat ../protobuf-options.txt` && \
            make -j4 && make install

          cd ..
          rm -rf build-$arch

          tree $artifact1

          arch=${{ matrix.arch }}
          if [[ $arch == arm64 ]]; then
            cd $artifact1
            7z -mx5 a ../${artifact1}.7z *
            cd ..
          fi
          echo ~~~~~~~~~~~~ arm64 build end ~~~~~~~~~~~~

          artifact2=""

          arch=${{ matrix.arch }}
          if [[ $arch == universal ]]; then
            echo ~~~~~~~~~~~~ x86_64 build begin ~~~~~~~~~~~~
            arch="x86_64"
            artifact2=protobuf-osx-$arch-${{ env.PROTOBUF_VERSION }}
            dst_dir=$PWD/$artifact2

            cflags="-arch $arch -isysroot macosx -Wno-unused-local-typedef -Wno-unused-function -DNDEBUG -g -O3 -pipe -fPIC -fcxx-exceptions"
            export LDFLAGS="-arch $arch -stdlib=libc++"
            export CFLAGS="$cflags"
            export CXXFLAGS="$cflags"

            mkdir build-$arch
            cd build-$arch

            cmake ../protobuf-${{ env.PROTOBUF_VERSION }} \
              -G "Unix Makefiles" \
              -DCMAKE_INSTALL_PREFIX=$dst_dir \
              -DCMAKE_OSX_ARCHITECTURES="$arch" -DCMAKE_OSX_SYSROOT=macosx \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 \
              `cat ../protobuf-options.txt` && \
              make -j4 && make install

            cd ..
            rm -rf build-$arch

            tree $artifact2
            cd $artifact2
            7z -mx5 a ../${artifact2}.7z *
            cd ..
            echo ~~~~~~~~~~~~ x86_64 build end ~~~~~~~~~~~~
          fi

          arch=${{ matrix.arch }}
          if [[ $arch == universal ]]; then
            echo ~~~~~~~~~~~~ make universal begin ~~~~~~~~~~~~
            arch=${{ matrix.arch }}
            artifact=protobuf-osx-$arch-${{ env.PROTOBUF_VERSION }}
            mkdir -p $PWD/$artifact/lib
            mkdir -p $PWD/$artifact/bin

            ocv_ver=${{ env.PROTOBUF_VERSION }}
            version=${ocv_ver%\.*}
            cp -R $PWD/$artifact2/include $PWD/$artifact
            lipo \
                $PWD/$artifact2/lib/libprotobuf-lite.a \
                $PWD/$artifact1/lib/libprotobuf-lite.a \
                -create -output $PWD/$artifact/lib/libprotobuf-lite.a
            lipo \
                $PWD/$artifact2/lib/libprotobuf.a \
                $PWD/$artifact1/lib/libprotobuf.a \
                -create -output $PWD/$artifact/lib/libprotobuf.a
            lipo \
                $PWD/$artifact2/lib/libprotoc.a \
                $PWD/$artifact1/lib/libprotoc.a \
                -create -output $PWD/$artifact/lib/libprotoc.a
            lipo \
                $PWD/$artifact2/bin/protoc \
                $PWD/$artifact1/bin/protoc \
                -create -output $PWD/$artifact/bin/protoc

            tree $artifact
            cd $artifact
            7z -mx5 a ../${artifact}.7z *
            cd ..

            rm -rf $WSP_ROOT/$artifact1
            rm -rf $WSP_ROOT/$artifact2
            echo ~~~~~~~~~~~~ make universal end ~~~~~~~~~~~~
          fi

          pwd && ls -la

          echo "update_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Upload artifact
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      uses: actions/upload-artifact@v4
      with:
          name: protobuf-osx-${{ matrix.arch }}-${{ env.PROTOBUF_VERSION }}
          path: protobuf-osx-${{ matrix.arch }}-${{ env.PROTOBUF_VERSION }}

    - name: Upload v${{ env.PROTOBUF_VERSION }}
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      uses: svenstaro/upload-release-action@v2
      with:
          file_glob: true
          file: "./*.7z"
          overwrite: true
          tag: protobuf-v${{ env.PROTOBUF_VERSION }}
          release_name: Protocol Buffers (cpp) v${{ env.PROTOBUF_VERSION }}
          body: |
              date: ${{ steps.vars.outputs.update_date }}

  build_with_windows-2019:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v7

    - name: Install or Download Dependencies
      run: |
        choco install curl unzip 7zip -y
        choco install cmake -y
        cmake --version
        mkdir deps
        cd deps && mkdir mingw64 && cd ..
        curl -L https://download.qt.io/official_releases/jom/jom.zip -o jom.zip
        unzip jom.zip -d ${{ github.workspace }}/deps/jom
        curl -L https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOBUF_VERSION }}/protobuf-cpp-3.${{ env.PROTOBUF_VERSION }}.tar.gz -o protobuf-cpp-3.${{ env.PROTOBUF_VERSION }}.tar.gz
        curl -L https://github.com/nonwill/mingw-distro/releases/download/mingw64-gcc15-crt_latest/mingw-w64+gcc-i686-all.7z -o mingw-w64_gcc-i686-all.7z
        curl -L https://github.com/nonwill/mingw-distro/releases/download/mingw64-gcc15-crt_latest/mingw-w64+gcc-x86_64-all.7z -o mingw-w64_gcc-x86_64-all.7z
        dir
        ${{ github.workspace }}/deps/jom/jom.exe /VERSION

        tar -xf protobuf-cpp-3.${{ env.PROTOBUF_VERSION }}.tar.gz
        mv protobuf-3.${{ env.PROTOBUF_VERSION }} protobuf-${{ env.PROTOBUF_VERSION }}
        cd protobuf-${{ env.PROTOBUF_VERSION }}
        cat ../protobuf-v3.21.12.patch | patch -p1 --verbose || exit 1
        cat ../protobuf-v3.21.12-a2859cc.patch | patch -p1 --verbose || exit 1
        cd ..

        7z -mx5 a ./protobuf-${{ env.PROTOBUF_VERSION }}-src.7z ./protobuf-${{ env.PROTOBUF_VERSION }}

    - name: MinGW Build Protocol Buffers ${{ env.PROTOBUF_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export USER_MINGW_DIR=$WSP_ROOT/deps/mingw64
        mkdir build
        echo ~~~~~~~~~~~~ mingw32 build prepare ~~~~~~~~~~~~
        7z x mingw-w64_gcc-i686-all.7z -r -o$USER_MINGW_DIR
        rm -f mingw-w64_gcc-i686-all.7z
        export PATH=$USER_MINGW_DIR/bin:$PATH
        gcc -v
        echo ~~~~~~~~~~~~ mingw32 build begin ~~~~~~~~~~~~
        cd build
        cmake ../protobuf-${{ env.PROTOBUF_VERSION }} \
            -G "MinGW Makefiles" \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-mingw64 \
            `cat ../protobuf-options.txt` && \
            mingw32-make -j4 && mingw32-make install
        rm -rf ./*
        cd ..
        strip $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-mingw64/bin/*.exe
        cd $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-mingw64
        7z -mx5 a ../protobuf-${{ env.PROTOBUF_VERSION }}-mingw64-i686.7z *
        cd ..
        echo ~~~~~~~~~~~~ mingw32 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-mingw64
        rm -rf $USER_MINGW_DIR/*
        echo ~~~~~~~~~~~~ mingw64 build prepare ~~~~~~~~~~~~
        7z x mingw-w64_gcc-x86_64-all.7z -r -o$USER_MINGW_DIR
        rm -f mingw-w64_gcc-x86_64-all.7z
        gcc -v
        echo ~~~~~~~~~~~~ mingw64 build begin ~~~~~~~~~~~~
        cd build
        cmake ../protobuf-${{ env.PROTOBUF_VERSION }} \
            -G "MinGW Makefiles" \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-mingw64 \
            `cat ../protobuf-options.txt` && \
            mingw32-make -j4 && mingw32-make install
        rm -rf ./*
        cd ..
        strip $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-mingw64/bin/*.exe
        cd $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-mingw64
        7z -mx5 a ../protobuf-${{ env.PROTOBUF_VERSION }}-mingw64-x86_64.7z *
        cd ..
        echo ~~~~~~~~~~~~ mingw64 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-mingw64

    - name: Setup msvc2019 x64 Environment
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
        toolset: 14.29

    - name: Get date and Cl version
      id: vars
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export USER_MINGW_DIR=$WSP_ROOT/deps/mingw64
        export PATH=$USER_MINGW_DIR/bin:$PATH
        echo "update_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "vc_install_dir=$VCToolsInstallDir" >> $GITHUB_OUTPUT
        echo "cl_exe_info=$(cl > cl_version 2>&1 && head -n 1 cl_version)" >> $GITHUB_OUTPUT
        echo "gcc_exe_info=$(gcc --version > gcc_version 2>&1 && head -n 1 gcc_version)" >> $GITHUB_OUTPUT
        rm -rf $USER_MINGW_DIR

    - name: msvc2019 x64 Build Protocol Buffers ${{ env.PROTOBUF_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export PATH=$WSP_ROOT/deps/jom:$PATH
        echo ~~~~~~~~~~~~ msvc2019 build begin ~~~~~~~~~~~~
        cl
        cd build
        cmake ../protobuf-${{ env.PROTOBUF_VERSION }} \
            -G "NMake Makefiles" \
            -DCMAKE_MAKE_PROGRAM=$WSP_ROOT/deps/jom/jom.exe \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-msvc2019-x64 \
            `cat ../protobuf-options.txt` && \
            jom -j4 && jom install
        rm -rf ./*
        cd ..
        cd $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-msvc2019-x64
        7z -mx5 a ../protobuf-${{ env.PROTOBUF_VERSION }}-msvc2019-x64.7z *
        cd ..
        echo ~~~~~~~~~~~~ msvc2019 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-msvc2019-x64

    - name: Setup msvc2019 x86 Environment
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: amd64_x86
        toolset: 14.29

    - name: msvc2019 x86 Build Protocol Buffers ${{ env.PROTOBUF_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export PATH=$WSP_ROOT/deps/jom:$PATH
        echo ~~~~~~~~~~~~ msvc2019 build begin ~~~~~~~~~~~~
        cl
        cd build
        cmake ../protobuf-${{ env.PROTOBUF_VERSION }} \
            -G "NMake Makefiles" \
            -DCMAKE_MAKE_PROGRAM=$WSP_ROOT/deps/jom/jom.exe \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-msvc2019-x86 \
            `cat ../protobuf-options.txt` && \
            jom -j4 && jom install
        rm -rf ./*
        cd ..
        cd $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-msvc2019-x86
        7z -mx5 a ../protobuf-${{ env.PROTOBUF_VERSION }}-msvc2019-x86.7z *
        cd ..
        echo ~~~~~~~~~~~~ msvc2019 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/protobuf-${{ env.PROTOBUF_VERSION }}-msvc2019-x86

    - name: Upload Protocol Buffers ${{ env.PROTOBUF_VERSION }}
      uses: svenstaro/upload-release-action@v2
      with:
        file_glob: true
        file: "./*.7z"
        overwrite: true
        tag: protobuf-v${{ env.PROTOBUF_VERSION }}
        release_name: Protocol Buffers (cpp) v${{ env.PROTOBUF_VERSION }}
        body: |
            date: ${{ steps.vars.outputs.update_date }}
            cl: ${{ steps.vars.outputs.cl_exe_info }}
            gcc: ${{ steps.vars.outputs.gcc_exe_info }}
            source: https://github.com/protocolbuffers/protobuf/releases/tag/v21.12
