name: Build icu4c with mingw64 and msvc2019

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-icu4c.yml'
      - 'mingw-gcc.txt'
      - 'cl_version'

env:
  ICU4C_VERSION: "78.3"
  ICU4C_VERREL: "78-3"

jobs:
  build_icu_console:
    if: true
    name: Build ${{ matrix.plat }}-${{ matrix.arch }} Release
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'x64'
            plat: 'mingw64'
            msystem: 'MINGW64'
            mpathtype: 'minimal'
          - arch: 'x86'
            plat: 'mingw64'
            msystem: 'MINGW32'
            mpathtype: 'minimal'
          - arch: 'x64'
            plat: 'msvc2019'
            msystem: 'MINGW64'
            mpathtype: 'inherit'
          - arch: 'x86'
            plat: 'msvc2019'
            msystem: 'MINGW32'
            mpathtype: 'inherit'
    steps:
    - name: Cache build result for ${{ env.ICU4C_VERSION }}-${{ matrix.plat }}-${{ matrix.arch }}
      id: cache-build-result
      uses: actions/cache@v4
      with:
        path: icu4c-${{ env.ICU4C_VERSION }}-${{ matrix.plat }}-${{ matrix.arch }}
        key: icu4c-${{ env.ICU4C_VERSION }}-${{ matrix.plat }}-${{ matrix.arch }}-cache-v2

    - name: Install msys2
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.msystem }}
        path-type: ${{ matrix.mpathtype }}
        update: true
        install: >-
            make
            unzip
            gzip
            p7zip
            m4
            nasm
            patch
            tar
            texinfo
            perl
            curl
            git
            tree

    - name: Download sources and Install Dependencies
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      shell: msys2 {0}
      run: |
        perl --version
        curl -L https://github.com/unicode-org/icu/releases/download/release-${{ env.ICU4C_VERSION }}/icu4c-${{ env.ICU4C_VERSION }}-sources.tgz -o icu4c-${{ env.ICU4C_VERSION }}.tgz
        ls -la

        plat=${{ matrix.plat }}
        arch=${{ matrix.arch }}

        if [[ $plat == mingw64 ]]; then
          mkdir -p $PWD/deps/mingw64

          if [[ $arch == x64 ]]; then
            arch=x86_64
          else
            arch=i686
          fi

          curl -L https://github.com/nonwill/mingw-distro/releases/download/mingw64-gcc15-crt_latest/mingw-w64+gcc-$arch-all.7z -o mingw-w64_gcc+$arch-all.7z
          ls -la

          7z x mingw-w64_gcc+$arch-all.7z -r -o$PWD/deps/mingw64

          ls $PWD/deps/mingw64
          $PWD/deps/mingw64/bin/gcc -v
        fi

        tar -xf icu4c-${{ env.ICU4C_VERSION }}.tgz

    - name: Setup msvc2019 x64 Environment
      if: steps.cache-build-result.outputs.cache-hit != 'true' && matrix.plat == 'msvc2019' && matrix.arch == 'x64'
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
        toolset: 14.29

    - name: Setup msvc2019 x86 Environment
      if: steps.cache-build-result.outputs.cache-hit != 'true' && matrix.plat == 'msvc2019' && matrix.arch == 'x86'
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x86
        toolset: 14.29

    - name: MinGW Build icu4c-${{ env.ICU4C_VERSION }}
      if: steps.cache-build-result.outputs.cache-hit != 'true' && matrix.plat == 'mingw64'
      shell: msys2 {0}
      run: |
        export PATH=$PWD/deps/mingw64/bin:$PATH
        export CPP=$PWD/deps/mingw64/bin/cpp.exe
        export CC=$PWD/deps/mingw64/bin/gcc.exe
        export CXX=$PWD/deps/mingw64/bin/g++.exe
        export AR=$PWD/deps/mingw64/bin/ar.exe
        export AS=$PWD/deps/mingw64/bin/as.exe
        export LD=$PWD/deps/mingw64/bin/ld.exe
        gcc -v
        artifact=icu4c-${{ env.ICU4C_VERSION }}-${{ matrix.plat }}-${{ matrix.arch }}
        dst_dir=$PWD/$artifact
        echo ~~~~~~~~~~~~ ${{ matrix.plat }}-${{ matrix.arch }} build begin ~~~~~~~~~~~~
        cd icu/source
        ./runConfigureICU MinGW --prefix=$dst_dir \
            CXXFLAGS=-std=gnu++17 && make -j 4 && make install && cd ../..

        tree ./$artifact
        cd $artifact
        strip ./bin/*.dll
        strip ./bin/*.exe
        7z -mx5 a ../${artifact}.7z *
        echo ~~~~~~~~~~~~ ${{ matrix.plat }}-${{ matrix.arch }} build end ~~~~~~~~~~~~

    - name: MSVC Build icu4c-${{ env.ICU4C_VERSION }}
      if: steps.cache-build-result.outputs.cache-hit != 'true' && matrix.plat == 'msvc2019'
      shell: msys2 {0}
      run: |
        mv /usr/bin/link /usr/bin/link1
        cl.exe
        artifact=icu4c-${{ env.ICU4C_VERSION }}-${{ matrix.plat }}-${{ matrix.arch }}
        dst_dir=$PWD/$artifact
        echo ~~~~~~~~~~~~ ${{ matrix.plat }}-${{ matrix.arch }} build begin ~~~~~~~~~~~~
        cd icu/source

        cd config && mv mh-unknown mh-unknown.raw && cp -v mh-msys-msvc mh-unknown && cd ..
        ./runConfigureICU MSYS/MSVC --prefix=$dst_dir \
            CXXFLAGS=/std:c++17 LDFLAGS=/DEFAULTLIB:msvcrt.lib && make -j 4 || mkdir -p data/out/tmp/dirs.timestamp
        make -j 4 install && cd ../..

        tree ./$artifact
        cd $artifact
        7z -mx5 a ../${artifact}.7z *
        echo ~~~~~~~~~~~~ ${{ matrix.plat }}-${{ matrix.arch }} build end ~~~~~~~~~~~~

    - name: Setup msvc2019 x64 Environment
      if: steps.cache-build-result.outputs.cache-hit != 'true' && matrix.plat == 'mingw64' && matrix.arch == 'x64'
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
        toolset: 14.29

    - name: Get date and Cl version
      if: steps.cache-build-result.outputs.cache-hit != 'true' && matrix.plat == 'mingw64' && matrix.arch == 'x64'
      id: vars
      shell: bash
      run: |
        export PATH=$PWD/deps/mingw64/bin:$PATH
        echo "update_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "vc_install_dir=$VCToolsInstallDir" >> $GITHUB_OUTPUT
        echo "cl_exe_info=$(cl > cl_version 2>&1 && head -n 1 cl_version)" >> $GITHUB_OUTPUT
        echo "gcc_exe_info=$(gcc --version > gcc_version 2>&1 && head -n 1 gcc_version)" >> $GITHUB_OUTPUT

    - name: Upload artifact
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: icu4c-${{ env.ICU4C_VERSION }}-${{ matrix.plat }}-${{ matrix.arch }}
        path: icu4c-${{ env.ICU4C_VERSION }}-${{ matrix.plat }}-${{ matrix.arch }}

    - name: Upload icu4c-${{ env.ICU4C_VERSION }}
      if: steps.cache-build-result.outputs.cache-hit != 'true'
      uses: svenstaro/upload-release-action@v2
      with:
        file_glob: true
        file: ./icu4c-${{ env.ICU4C_VERSION }}-*.7z
        overwrite: true
        tag: icu4c-${{ env.ICU4C_VERSION }}
        release_name: icu4c-${{ env.ICU4C_VERSION }}

    - name: Upload icu4c-${{ env.ICU4C_VERSION }}.tgz
      if: steps.cache-build-result.outputs.cache-hit != 'true' && matrix.plat == 'mingw64' && matrix.arch == 'x64'
      uses: svenstaro/upload-release-action@v2
      with:
        file_glob: true
        file: ./icu4c-${{ env.ICU4C_VERSION }}.tgz
        overwrite: true
        tag: icu4c-${{ env.ICU4C_VERSION }}
        release_name: icu4c-${{ env.ICU4C_VERSION }}
        body: |
          date: ${{ steps.vars.outputs.update_date }}
          cl: ${{ steps.vars.outputs.cl_exe_info }}
          gcc: ${{ steps.vars.outputs.gcc_exe_info }}

  # Windows MSVC distribution release
  build_with_windows-msvc-2019:
    if: false
    needs: build_icu_console
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: 'x64'
            plat: 'x64'
            win_ver: 'Win64'
          - arch: 'x86'
            plat: 'Win32'
            win_ver: 'Win32'
    steps:
    - uses: actions/checkout@v7

    - name: Install or Download Dependencies
      run: |
        mkdir deps
        cd deps && mkdir mingw64 && cd ..
        curl -L https://github.com/unicode-org/icu/releases/download/release-${{ env.ICU4C_VERSION }}/icu4c-${{ env.ICU4C_VERSION }}-sources.tgz -o icu4c-${{ env.ICU4C_VERSION }}.tgz
        dir
        tar -xf icu4c-${{ env.ICU4C_VERSION }}.tgz
        dir

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v3
      with:
        vs-version: 16.11

    - name: Build Solution
      run: msbuild icu/source/allinone/allinone.sln /p:Configuration=Release /p:Platform=${{ matrix.plat }} /p:SkipUWP=true
    - name: "Run PowerShell: Distrelease script (${{ matrix.arch }})"
      shell: pwsh
      run: |
        cd ./icu/
        ./packaging/distrelease.ps1 -arch ${{ matrix.arch }}

    - name: Extract ICU version and rename zip file
      id: set-zip-name
      run: |
        $newZipName = "icu4c-${{ env.ICU4C_VERSION }}-msvc2019-${{ matrix.arch }}"
        Write-Host "New Zip Name: $newZipName"
        # Rename the existing zip file
        cd icu\source\dist\ && ls -l .
        Rename-Item -Path icu-windows.zip -NewName "${newZipName}.zip"
        ls -l .

    - name: Upload icu4c-${{ env.ICU4C_VERSION }}
      uses: softprops/action-gh-release@v3
      with:
        tag_name: icu4c-${{ env.ICU4C_VERSION }}
        name: icu4c-${{ env.ICU4C_VERSION }}
        draft: false
        prerelease: false
        make_latest: true
        files: |
          ./icu/source/dist/icu4c-${{ env.ICU4C_VERSION }}-*.zip
