name: Build OpenCV with mingw64 and msvc2019

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/build-opencv.yml'
      - 'opencv-options.txt'
      - 'mingw-gcc.txt'
      - 'cl_version'

env:
  OPENCV_VERSION: "3.4.20"

jobs:
  build_with_windows-2019:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4

    - name: Install or Download Dependencies
      run: |
        choco install curl unzip 7zip -y
        choco install cmake -y
        cmake --version
        mkdir deps
        cd deps && mkdir mingw64 && cd ..
        curl -L https://download.qt.io/official_releases/jom/jom.zip -o jom.zip
        unzip jom.zip -d ${{ github.workspace }}/deps/jom
        curl -L https://github.com/opencv/opencv/archive/${{ env.OPENCV_VERSION }}.tar.gz -o opencv-${{ env.OPENCV_VERSION }}.tar.gz
        curl -L https://github.com/nonwill/mingw-distro/releases/download/mingw64-gcc-crt_latest/mingw-w64+gcc-i686-all.7z -o mingw-w64_gcc-i686-all.7z
        curl -L https://github.com/nonwill/mingw-distro/releases/download/mingw64-gcc-crt_latest/mingw-w64+gcc-x86_64-all.7z -o mingw-w64_gcc-x86_64-all.7z
        dir
        ${{ github.workspace }}/deps/jom/jom.exe /VERSION

    - name: MinGW Build OpenCV-${{ env.OPENCV_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export USER_MINGW_DIR=$WSP_ROOT/deps/mingw64
        tar -xf opencv-${{ env.OPENCV_VERSION }}.tar.gz
        rm -f opencv-${{ env.OPENCV_VERSION }}.tar.gz
        mkdir build
        echo ~~~~~~~~~~~~ mingw32 build prepare ~~~~~~~~~~~~
        7z x mingw-w64_gcc-i686-all.7z -r -o$USER_MINGW_DIR
        rm -f mingw-w64_gcc-i686-all.7z
        export PATH=$USER_MINGW_DIR/bin:$PATH
        gcc -v
        echo ~~~~~~~~~~~~ mingw32 build begin ~~~~~~~~~~~~
        cd build
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "MinGW Makefiles" \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64 \
            `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            mingw32-make -j4 && mingw32-make install
        rm -rf ./*
        cd ..
        strip $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64/x64/mingw/bin/*.dll
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-mingw64-i686.7z *
        cd ..
        echo ~~~~~~~~~~~~ mingw32 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64
        rm -rf $USER_MINGW_DIR/*
        echo ~~~~~~~~~~~~ mingw64 build prepare ~~~~~~~~~~~~
        7z x mingw-w64_gcc-x86_64-all.7z -r -o$USER_MINGW_DIR
        rm -f mingw-w64_gcc-x86_64-all.7z
        gcc -v
        echo ~~~~~~~~~~~~ mingw64 build begin ~~~~~~~~~~~~
        cd build
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "MinGW Makefiles" \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64 \
            `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            mingw32-make -j4 && mingw32-make install
        rm -rf ./*
        cd ..
        strip $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64/x64/mingw/bin/*.dll
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-mingw64-x86_64.7z *
        cd ..
        echo ~~~~~~~~~~~~ mingw64 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-mingw64

    - name: Setup msvc2019 x64 Environment
      uses: ilammy/msvc-dev-cmd@v1

    - name: Get date and Cl version
      id: vars
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export USER_MINGW_DIR=$WSP_ROOT/deps/mingw64
        export PATH=$USER_MINGW_DIR/bin:$PATH
        echo "update_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        echo "vc_install_dir=$VCToolsInstallDir" >> $GITHUB_OUTPUT
        echo "cl_exe_info=$(cl > cl_version 2>&1 && head -n 1 cl_version)" >> $GITHUB_OUTPUT
        echo "gcc_exe_info=$(gcc --version > gcc_version 2>&1 && head -n 1 gcc_version)" >> $GITHUB_OUTPUT
        rm -rf $USER_MINGW_DIR

    - name: msvc2019 x64 Build OpenCV-${{ env.OPENCV_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export PATH=$WSP_ROOT/deps/jom:$PATH
        echo ~~~~~~~~~~~~ msvc2019 build begin ~~~~~~~~~~~~
        cl
        cd build
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "NMake Makefiles" \
            -DCMAKE_MAKE_PROGRAM=$WSP_ROOT/deps/jom/jom.exe \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x64 \
            `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            jom -j4 && jom install
        rm -rf ./*
        cd ..
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x64
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-msvc2019-x64.7z *
        cd ..
        echo ~~~~~~~~~~~~ msvc2019 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x64

    - name: Setup msvc2019 x86 Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: msvc2019 x86 Build OpenCV-${{ env.OPENCV_VERSION }}
      shell: bash
      run: |
        export WSP_ROOT=$PWD
        export PATH=$WSP_ROOT/deps/jom:$PATH
        echo ~~~~~~~~~~~~ msvc2019 build begin ~~~~~~~~~~~~
        cl
        cd build
        cmake ../opencv-${{ env.OPENCV_VERSION }} \
            -G "NMake Makefiles" \
            -DCMAKE_MAKE_PROGRAM=$WSP_ROOT/deps/jom/jom.exe \
            -DCMAKE_INSTALL_PREFIX=$WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x86 \
            `cat ../opencv-options.txt` \
            -DBUILD_opencv_world=ON && \
            jom -j4 && jom install
        rm -rf ./*
        cd ..
        cd $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x86
        7z -mx5 a ../opencv-${{ env.OPENCV_VERSION }}-msvc2019-x86.7z *
        cd ..
        echo ~~~~~~~~~~~~ msvc2019 build end ~~~~~~~~~~~~
        rm -rf $WSP_ROOT/opencv-${{ env.OPENCV_VERSION }}-msvc2019-x86

    - uses: andreaswilli/delete-release-assets-action@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag: opencv-${{ env.OPENCV_VERSION }}
        deleteOnlyFromDrafts: false

    - name: Upload opencv-${{ env.OPENCV_VERSION }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: opencv-${{ env.OPENCV_VERSION }}
        name: Latest build of opencv-${{ env.OPENCV_VERSION }}
        body: |
          date: ${{ steps.vars.outputs.update_date }}
          cl: ${{ steps.vars.outputs.cl_exe_info }}
          gcc: ${{ steps.vars.outputs.gcc_exe_info }}
        draft: false
        prerelease: false
        make_latest: true
        files: |
          ./opencv-${{ env.OPENCV_VERSION }}-*.7z
