name: get-latest-msvc-2019-build-tools

on: 
    issue_comment: 
        types: [created]

jobs:
    get_latest_msvc2019:
        name: Get latest msvc 2019 build tools
        if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'get_msvc2019') && github.event.issue.user.login == 'nonwill' && github.triggering_actor == 'nonwill' && github.event.comment.user.login == 'nonwill' }}
        runs-on: windows-2022
        steps:
                - uses: actions/checkout@v4
                - uses: ilammy/msvc-dev-cmd@v1
                  with: 
                        toolset: 14.29
                - name: Get version information
                  id: vars
                  shell: bash
                  run: |
                        echo "update_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
                        echo "vc_install_dir=$VCToolsInstallDir" >> $GITHUB_OUTPUT
                        echo "cl_exe_info=$(cl > cl_version 2>&1 && head -n 1 cl_version)" >> $GITHUB_OUTPUT
                - uses: GuillaumeFalourd/git-commit-push@v1.3

                - name: msvc-build tools
                  shell: cmd
                  run: |
                        echo winSdkVer=%WindowsSdkVersion%
                        echo winSdkDir=%WindowsSdkDir%
                        echo vcToolsInstallDir=%VCToolsInstallDir%
                        cl.exe
                        echo Copy Llvm Tools
                        mkdir Llvm && cd Llvm && mkdir bin && cd bin
                        copy /Y "%vcToolsInstallDir%..\..\Llvm\bin\clang-format.exe" .
                        copy /Y "%vcToolsInstallDir%..\..\Llvm\bin\git-clang-format" .
                        copy /Y "%vcToolsInstallDir%..\..\Llvm\bin\clang-tidy.exe" .
                        cd .. && mkdir x64 && cd x64 && mkdir bin && cd bin
                        copy /Y "%vcToolsInstallDir%..\..\Llvm\x64\bin\clang-format.exe" .
                        copy /Y "%vcToolsInstallDir%..\..\Llvm\x64\bin\git-clang-format" .
                        copy /Y "%vcToolsInstallDir%..\..\Llvm\x64\bin\clang-tidy.exe" .
                        cd .. && cd .. && cd ..
                        mkdir vcToolsInstallDir Auxiliary
                        echo Copy VC Auxiliary Build
                        cd Auxiliary && mkdir Build
                        xcopy "%vcToolsInstallDir%../../../Auxiliary/Build" Build /Y /E /I /Q /H /C
                        cd .. && cd vcToolsInstallDir && mkdir Auxiliary crt include atlmfc bin lib
                        echo Copy Auxiliary, crt, include
                        xcopy "%vcToolsInstallDir%Auxiliary" Auxiliary /Y /E /I /Q /H /C
                        xcopy "%vcToolsInstallDir%crt" crt /Y /E /I /Q /H /C
                        xcopy "%vcToolsInstallDir%include" include /Y /E /I /Q /H /C
                        cd atlmfc && mkdir include lib src
                        echo Copy atlmfc: include, src
                        xcopy "%vcToolsInstallDir%atlmfc/include" include /Y /E /I /Q /H /C
                        xcopy "%vcToolsInstallDir%atlmfc/src" src /Y /E /I /Q /H /C
                        cd lib && mkdir x64 x86
                        echo Copy atlmfc: lib - x64 and x86
                        xcopy "%vcToolsInstallDir%atlmfc/lib/x64" x64 /Y /E /I /Q /H /C
                        xcopy "%vcToolsInstallDir%atlmfc/lib/x86" x86 /Y /E /I /Q /H /C
                        cd .. && cd .. && cd bin && mkdir Hostx64 Hostx86
                        cd Hostx64 && mkdir x64 x86
                        echo Copy bin: Hostx64 - x64 and x86
                        xcopy "%vcToolsInstallDir%bin/Hostx64/x64" x64 /Y /E /I /Q /H /C
                        xcopy "%vcToolsInstallDir%bin/Hostx64/x86" x86 /Y /E /I /Q /H /C
                        cd .. && cd Hostx86 && mkdir x64 x86
                        echo Copy bin: Hostx86 - x64 and x86
                        xcopy "%vcToolsInstallDir%bin/Hostx86/x64" x64 /Y /E /I /Q /H /C
                        xcopy "%vcToolsInstallDir%bin/Hostx86/x86" x86 /Y /E /I /Q /H /C
                        cd .. && cd ..  && cd lib && mkdir x64 x86
                        echo Copy lib: x64 and x86
                        xcopy "%vcToolsInstallDir%lib/x64" x64 /Y /E /I /Q /H /C
                        xcopy "%vcToolsInstallDir%lib/x86" x86 /Y /E /I /Q /H /C
                        cd ..
                        del /S /Q *.pdb
                        cd ..
                        7z -mx5 a ./Llvm.7z ./Llvm
                        7z -mx5 a ./vc_Auxiliary.7z ./Auxiliary
                        7z -mx5 a ./vcToolsInstallDir.7z ./vcToolsInstallDir

                - name: Delete msvc2019_latest assets
                  uses: andreaswilli/delete-release-assets-action@v4.0.0
                  with:
                        github_token: ${{ secrets.GITHUB_TOKEN }}
                        tag: msvc2019_latest
                        deleteOnlyFromDrafts: false

                - name: Create Release and Upload Release Asset
                  uses: softprops/action-gh-release@v2
                  with:
                        tag_name: msvc2019_latest
                        name: Latest msvc-2019 build tools for Windows x86/x64
                        body: |
                                date: ${{ steps.vars.outputs.update_date }}
                                from: ${{ steps.vars.outputs.vc_install_dir }}
                                cl.exe: ${{ steps.vars.outputs.cl_exe_info }}
                        draft: false
                        prerelease: false
                        files: |
                                ./*.7z