name: test-github-actions

on: 
    issue_comment: 
        types: [created]

jobs:
    test_action:
        name: Test Actions
        if: ${{ !github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'test_actions') && github.event.issue.user.login == 'nonwill' && github.triggering_actor == 'nonwill' && github.event.comment.user.login == 'nonwill' }}
        runs-on: ubuntu-latest
        steps:
                - name: Test github.event.issue
                  shell: bash
                  run: |
                        echo "github.event.issue.user.login = ${{ github.event.issue.user.login }}"
                        echo "github.triggering_actor = ${{ github.triggering_actor }}"
                        echo "github.event.comment.user.login = ${{ github.event.comment.user.login }}"
